### ISSUE TITLE
Enterprise github metrics

### ISSUE THREAD

**Issue by bergamoyat** [josephlewis42/githubbeat#18]
We have an on premise enterprise github instance setup within the organization. Could the github baseurl be put in as a configurable param in the config file ?

**Comment by josephlewis42** [comment]
Hi @bergamoyat,

I just added the feature in the most recent commit. You can use the following two configuration properties to configure Enterprise support. Let me know how it goes for you!

```
  # The base URL of the API.
  # Leave this blank if you want to connect to GitHub.com
  enterprise.base_url: ""
  # The upload URL of the API, typically this is the same as the base_url. 
  # Leave this blank if you want to connect to GitHub.com
  enterprise.upload_url: ""
```
