### ISSUE TITLE
Unsuccessful conversion to generic event

### ISSUE THREAD

**Issue by markwalkom** [josephlewis42/githubbeat#24]
First up, thanks heaps for maintaining this fork, it's really appreciated!

I downloaded this the other day to have a play and have run into a few problems. I've put my log file right [here](https://gist.github.com/markwalkom/6f75d4ce2c8d435a2d9b83990e456676).

The first issue I see is [line 16](https://gist.github.com/markwalkom/6f75d4ce2c8d435a2d9b83990e456676#file-gistfile1-txt-L12), where it says `Unsuccessful conversion to generic event`. I am not sure what else to provide here, but the log might make that clearer.

The second issue I see is [here](https://gist.github.com/markwalkom/6f75d4ce2c8d435a2d9b83990e456676#file-gistfile1-txt-L16) - `Unsuccessful conversion to generic event` again.

And the relevant error is;
```
type":"mapper_parsing_exception","reason":"failed to parse field [issues.error] of type [text]","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:12631"}}
```

I had a look at the json output from the log, and it [doesn't look like](https://gist.github.com/markwalkom/6f75d4ce2c8d435a2d9b83990e456676#file-event-json) that is an object. But I may be/probably am missing something.

I [updated the included template](https://gist.github.com/markwalkom/6f75d4ce2c8d435a2d9b83990e456676#file-new_template-json) to remove any `issues.error` I could find, to let Elasticsearch just dynamically map it, but that also didn't work and I got the same error.

**Comment by josephlewis42** [comment]
Hi @markwalkom, I've updated the code and [released a new version](https://github.com/josephlewis42/githubbeat/releases/tag/v1.0.2) to include the fix, please take a look when you get a chance and tell me if it worked for you.

**Comment by markwalkom** [comment]
```
$ curl -H "Content-Type: application/json" 0:9206/_cat/indices/githubbeat-7.0.0-alpha1-2019.02.07?v
health status index                              uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   githubbeat-7.0.0-alpha1-2019.02.07 NhZQU1FtTreiUaLPRer9pw   5   1        329            0     32.4kb         32.4kb
```

Thank you for the quick turn around here!
